language: go
branches:
  only:
   - master
   - working
install:
 - go get github.com/racker/perigee
script:
 - go test -v github.com/racker/gorax/v2.0/identity
 - go test -v github.com/racker/gorax/v2.0/cloud/servers

